-- ThriveDeck — Peptides (Module 5) migration — SAFETY CRITICAL
-- Run this in the Supabase SQL editor (or via prisma migrate + manual RLS).
-- Prisma manages table structure; RLS policies must be applied via SQL like this,
-- because Prisma does not manage Postgres row-level security.
--
-- Every dose/frequency column in this module RECORDS what the user's licensed
-- healthcare provider prescribed. Nothing here computes, defaults, or suggests
-- a dose — see CLAUDE.md § Health & safety rules.

-- =============================================================
-- care_providers — the user's own providers and pharmacies.
-- Referenced (softly) by peptides for prescriber/pharmacy info.
-- =============================================================
create table if not exists public.care_providers (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null references auth.users(id) on delete cascade,
  kind        text not null check (kind in ('PROVIDER','PHARMACY')),
  name        text not null,
  phone       text,
  email       text,
  address     text,
  notes       text,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create index if not exists care_providers_user_kind_idx
  on public.care_providers (user_id, kind);

alter table public.care_providers enable row level security;

create policy "Users can view own care providers"
  on public.care_providers for select
  using (auth.uid() = user_id);

create policy "Users can insert own care providers"
  on public.care_providers for insert
  with check (auth.uid() = user_id);

create policy "Users can update own care providers"
  on public.care_providers for update
  using (auth.uid() = user_id);

create policy "Users can delete own care providers"
  on public.care_providers for delete
  using (auth.uid() = user_id);

drop trigger if exists set_care_providers_updated_at on public.care_providers;
create trigger set_care_providers_updated_at
  before update on public.care_providers
  for each row execute function public.set_updated_at();

-- =============================================================
-- peptides — one row per peptide the user tracks. dose_amount /
-- dose_unit / frequency are transcriptions of the user's own
-- prescription, entered by the user, never generated by the app.
-- =============================================================
create table if not exists public.peptides (
  id              uuid primary key default gen_random_uuid(),
  user_id         uuid not null references auth.users(id) on delete cascade,
  name            text not null,
  status          text not null default 'ACTIVE'
                    check (status in ('ACTIVE','PAUSED','COMPLETED')),
  dose_amount     double precision check (dose_amount > 0),
  dose_unit       text check (dose_unit in ('MG','MCG','IU','ML','UNITS')),
  frequency       text, -- free text as the provider phrased it, e.g. "5 days on, 2 off"
  started_on      date,
  ended_on        date,
  lot_number      text,
  expires_on      date,
  provider_id     uuid references public.care_providers(id) on delete set null,
  pharmacy_id     uuid references public.care_providers(id) on delete set null,
  protocol_notes  text,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

create index if not exists peptides_user_status_idx
  on public.peptides (user_id, status);

alter table public.peptides enable row level security;

create policy "Users can view own peptides"
  on public.peptides for select
  using (auth.uid() = user_id);

create policy "Users can insert own peptides"
  on public.peptides for insert
  with check (auth.uid() = user_id);

create policy "Users can update own peptides"
  on public.peptides for update
  using (auth.uid() = user_id);

create policy "Users can delete own peptides"
  on public.peptides for delete
  using (auth.uid() = user_id);

drop trigger if exists set_peptides_updated_at on public.peptides;
create trigger set_peptides_updated_at
  before update on public.peptides
  for each row execute function public.set_updated_at();

-- =============================================================
-- peptide_injections — injection history, including MISSED doses.
-- peptide_name and dose fields are snapshots at log time so history
-- survives edits/deletes in the peptides table (soft pointer).
-- =============================================================
create table if not exists public.peptide_injections (
  id           uuid primary key default gen_random_uuid(),
  user_id      uuid not null references auth.users(id) on delete cascade,
  peptide_id   uuid references public.peptides(id) on delete set null,
  peptide_name text not null,
  status       text not null default 'LOGGED' check (status in ('LOGGED','MISSED')),
  injected_at  timestamptz not null,
  dose_amount  double precision check (dose_amount > 0),
  dose_unit    text check (dose_unit in ('MG','MCG','IU','ML','UNITS')),
  site         text check (site in
                 ('ABDOMEN_LEFT','ABDOMEN_RIGHT','THIGH_LEFT','THIGH_RIGHT',
                  'GLUTE_LEFT','GLUTE_RIGHT','ARM_LEFT','ARM_RIGHT','OTHER')),
  lot_number   text,
  notes        text,
  created_at   timestamptz not null default now()
);

create index if not exists peptide_injections_user_injected_idx
  on public.peptide_injections (user_id, injected_at desc);

create index if not exists peptide_injections_peptide_idx
  on public.peptide_injections (peptide_id);

alter table public.peptide_injections enable row level security;

create policy "Users can view own peptide injections"
  on public.peptide_injections for select
  using (auth.uid() = user_id);

create policy "Users can insert own peptide injections"
  on public.peptide_injections for insert
  with check (auth.uid() = user_id);

create policy "Users can update own peptide injections"
  on public.peptide_injections for update
  using (auth.uid() = user_id);

create policy "Users can delete own peptide injections"
  on public.peptide_injections for delete
  using (auth.uid() = user_id);

-- =============================================================
-- peptide_reminders — dose / refill / lab / appointment reminders.
-- Marking a repeating reminder done advances due_at by
-- repeat_every_days; a one-off flips active to false.
-- =============================================================
create table if not exists public.peptide_reminders (
  id                uuid primary key default gen_random_uuid(),
  user_id           uuid not null references auth.users(id) on delete cascade,
  peptide_id        uuid references public.peptides(id) on delete set null,
  kind              text not null check (kind in ('DOSE','REFILL','LAB','APPOINTMENT')),
  title             text not null,
  due_at            timestamptz not null,
  repeat_every_days integer check (repeat_every_days > 0),
  active            boolean not null default true,
  notes             text,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);

create index if not exists peptide_reminders_user_active_due_idx
  on public.peptide_reminders (user_id, active, due_at);

alter table public.peptide_reminders enable row level security;

create policy "Users can view own peptide reminders"
  on public.peptide_reminders for select
  using (auth.uid() = user_id);

create policy "Users can insert own peptide reminders"
  on public.peptide_reminders for insert
  with check (auth.uid() = user_id);

create policy "Users can update own peptide reminders"
  on public.peptide_reminders for update
  using (auth.uid() = user_id);

create policy "Users can delete own peptide reminders"
  on public.peptide_reminders for delete
  using (auth.uid() = user_id);

drop trigger if exists set_peptide_reminders_updated_at on public.peptide_reminders;
create trigger set_peptide_reminders_updated_at
  before update on public.peptide_reminders
  for each row execute function public.set_updated_at();

-- =============================================================
-- peptide_side_effects — user-reported side effects. peptide_name
-- is a snapshot; peptide_id is a soft pointer.
-- =============================================================
create table if not exists public.peptide_side_effects (
  id           uuid primary key default gen_random_uuid(),
  user_id      uuid not null references auth.users(id) on delete cascade,
  peptide_id   uuid references public.peptides(id) on delete set null,
  peptide_name text,
  occurred_at  timestamptz not null,
  severity     text not null check (severity in ('MILD','MODERATE','SEVERE')),
  description  text not null,
  created_at   timestamptz not null default now()
);

create index if not exists peptide_side_effects_user_occurred_idx
  on public.peptide_side_effects (user_id, occurred_at desc);

alter table public.peptide_side_effects enable row level security;

create policy "Users can view own peptide side effects"
  on public.peptide_side_effects for select
  using (auth.uid() = user_id);

create policy "Users can insert own peptide side effects"
  on public.peptide_side_effects for insert
  with check (auth.uid() = user_id);

create policy "Users can update own peptide side effects"
  on public.peptide_side_effects for update
  using (auth.uid() = user_id);

create policy "Users can delete own peptide side effects"
  on public.peptide_side_effects for delete
  using (auth.uid() = user_id);

-- =============================================================
-- peptide_journal_entries — free-form journal, optionally tied to
-- a peptide (snapshot + soft pointer, same as above).
-- =============================================================
create table if not exists public.peptide_journal_entries (
  id           uuid primary key default gen_random_uuid(),
  user_id      uuid not null references auth.users(id) on delete cascade,
  peptide_id   uuid references public.peptides(id) on delete set null,
  peptide_name text,
  entry_date   date not null,
  content      text not null,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

create index if not exists peptide_journal_entries_user_date_idx
  on public.peptide_journal_entries (user_id, entry_date desc);

alter table public.peptide_journal_entries enable row level security;

create policy "Users can view own peptide journal entries"
  on public.peptide_journal_entries for select
  using (auth.uid() = user_id);

create policy "Users can insert own peptide journal entries"
  on public.peptide_journal_entries for insert
  with check (auth.uid() = user_id);

create policy "Users can update own peptide journal entries"
  on public.peptide_journal_entries for update
  using (auth.uid() = user_id);

create policy "Users can delete own peptide journal entries"
  on public.peptide_journal_entries for delete
  using (auth.uid() = user_id);

drop trigger if exists set_peptide_journal_entries_updated_at on public.peptide_journal_entries;
create trigger set_peptide_journal_entries_updated_at
  before update on public.peptide_journal_entries
  for each row execute function public.set_updated_at();
